# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: walberla/latex

build:
  script:
    - xelatex -synctex=1 -interaction=nonstopmode latex/NelsonCruz-CV.tex
    - xelatex -synctex=1 -interaction=nonstopmode latex/NelsonCruz-CV-en.tex
    - echo "Compiled pdf"
  artifacts:
    paths:
      - "*.pdf"
